{
 "title": "Systemd Service",
 "tags": [ "systemd" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_systemd_unit_state,instance)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(node_systemd_unit_state{type!=\"\",instance=~\"$instance.*\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name!~\".*systemd.*\",instance=~\"$instance.*\",type!=\"\"} == 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"$service\", state=\"active\", instance=~\"$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"$instance.*\",id=\"/system.slice/$service\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$instance.*\",name=\"$service\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$instance.*\",id=\"/system.slice/$service\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$instance.*\",id=\"/system.slice/$service\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Log Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(detected_level) (count_over_time({instance=\"$instance\", unit=\"$service\"} [1m]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{unit=\"$service\", instance=\"$instance\"} |= ``"
    }
   ]
  }
 ]
}