on: [push]
jobs:
  build:
    runs-on: nixos-x86_64-linux
    concurrency:
      cancel-in-progress: false
    strategy:
      matrix:
        flake: [mentat, muadib, prime]
    steps:
      - uses: actions/checkout@v6
      - name: Fetch submodules
        run: |
          git config url."https://x-access-token:${{ secrets.FORGEJO_PAT }}@git.keyruu.de/".insteadOf "ssh://git@git.lab.keyruu.de:222/"
          git submodule update --init --recursive
      - name: Build
        run: nixos-rebuild build --flake .?submodules=1#${{ matrix.flake }} --max-jobs 1

