on:
  push:
    paths:
      - nix/packages/freshrss-youlag.nix
  pull_request:
    paths:
      - nix/packages/freshrss-youlag.nix

jobs:
  update-freshrss-youlag:
    runs-on: nixos-x86_64-linux
    uses: ./.forgejo/workflows/update-hash.yml
    with:
      package: freshrss-youlag 
    secrets: inherit
