on:
  push:
    paths:
      - nix/packages/freshrss-reddit.nix

jobs:
  update-freshrss-reddit:
    runs-on: nixos-x86_64-linux
    uses: ./.forgejo/workflows/update-hash.yml
    with:
      package: freshrss-reddit 
    secrets: inherit
