on:
  pull_request:
    paths:
      - nix/packages/tf-cloudflare.nix
      - flake.lock

jobs:
  update-tf-cloudflare:
    runs-on: nixos-x86_64-linux
    uses: ./.forgejo/workflows/update-hash.yml
    with:
      package: tf-cloudflare
    secrets: inherit