on:
  pull_request:
    paths:
      - nix/packages/tf-hcloud.nix
      - flake.lock

jobs:
  update-tf-hcloud:
    runs-on: nixos-x86_64-linux
    uses: ./.forgejo/workflows/update-hash.yml
    with:
      package: tf-hcloud
    secrets: inherit