#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#yabai -m config debug_output on

#!/usr/bin/env sh

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focused"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger window_title_changed"

# bar settings
yabai -m config external_bar                 all:35:10

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off

#yabai -m config active_window_opacity        1.0
#yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
#yabai -m config top_padding                  10
#yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# ===== Rules ==================================

yabai -m rule --add label="Arc" app="^Arc$" space=^7
yabai -m rule --add label="IntelliJ" app="^IntelliJ IDEA.*" space=^8
yabai -m rule --add label="Warp" app="^Warp$" space=^9
yabai -m rule --add label="Kitty" app="^kitty$" space=^9
yabai -m rule --add label="Alacritty" app="^Alacritty$" space=^9
yabai -m rule --add label="WezTerm" app="^WezTerm$" space=^9
yabai -m rule --add label="Outlook" app="^Microsoft Outlook$" space=^1
yabai -m rule --add label="Teams" app="^Microsoft Teams$" space=^2
yabai -m rule --add label="Slack" app="^Slack$" space=^2
yabai -m rule --add label="Obsidian" app="^Obsidian$" space=^3
# yabai -m rule --add label="Heynote" app="^Heynote$" space=^3
yabai -m rule --add label="Spotify" app="^Spotify$" space=^4
yabai -m rule --add label="Finder" app="^Finder$" space=^5
yabai -m rule --add label="Messages" app="^Messages$" space=^6

yabai -m rule --add label="Heynote" app="^Heynote$" scratchpad=heynote grid=11:11:1:1:9:9

yabai -m signal --add label="Change Space after launch" event=window_created action="$HOME/.config/yabai/changeSpaceAfterCreation.sh"

yabai -m rule --add label="Parallels" app="^Parallels Desktop$" manage=off
yabai -m rule --add label="iTerm" app="^IntelliJ IDEA.*" title="^Push Commits .*" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Raycast" app="^Raycast$" title=".*" manage=off
yabai -m rule --add label="PastePal" app="^PastePal$" title=".*" manage=off
yabai -m rule --add label="Preferences" app=".*" title="Preferences" manage=off
yabai -m rule --add label="GIMP" app="^GIMP$" title=".*" manage=off
yabai -m rule --add label="LuLu" app=".*" title="LuLu Alert" manage=off
yabai -m rule --add label="Affinity" app="^Affinity.*" title=".*" manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# Disable animations when opening and closing windows.
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

# Accelerated playback when adjusting the window size.
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

echo "yabai configuration loaded.."
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'
