inputs:
  token:
    required: true
runs:
  using: composite
  steps:
    - name: Fetch submodules
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        git submodule init
        git -c "submodule.nix/modules/private.url=https://x-access-token:${TOKEN}@git.keyruu.de/lucas/privateflakes.git" submodule update --recursive