inputs:
  token:
    required: true
runs:
  using: composite
  steps:
    - name: Fetch submodules
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        # ponytail: assume all submodules use https://. Add ssh:// branch when needed.
        git submodule init
        mapfile -t lines < <(git config -f .gitmodules --get-regexp '^submodule\..*\.url')
        for line in "${lines[@]}"; do
            key="${line%% *}"
            url="${line#* }"
            set -- "$@" -c "${key}=${url/https:\/\//https://x-access-token:${TOKEN}@}"
        done
        git "$@" submodule update --recursive